# Generated by Django 4.2.2 on 2023-07-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldier', '0003_soldierpersonaldata_delete_soldier_personaldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldierpersonaldata',
            name='family_detail',
        ),
        migrations.AlterField(
            model_name='soldierpersonaldata',
            name='upgradation_cadre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='soldierpersonaldata',
            table='soldier_soldierpersonaldata',
        ),
    ]
