# Generated by Django 4.2.2 on 2023-07-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldier', '0004_remove_soldierpersonaldata_family_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BtyChamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.CharField(max_length=255)),
                ('P_bty', models.IntegerField()),
                ('Q_bty', models.IntegerField()),
                ('R_bty', models.IntegerField()),
                ('S_bty', models.IntegerField()),
            ],
        ),
    ]
