# Generated by Django 4.2.2 on 2023-07-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldier', '0005_btychamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldierBtyChamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.CharField(max_length=200)),
                ('P_bty', models.IntegerField(default=0)),
                ('Q_bty', models.IntegerField(default=0)),
                ('R_bty', models.IntegerField(default=0)),
                ('S_bty', models.IntegerField(default=0)),
            ],
        ),
    ]
